development:
  adapter: postgresql
  encoding: unicode
  database: liftilog_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: liftilog_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: liftilog_production
  pool: 5
